# Databricks notebook source
# Auto-generated by DPBA — Component 3: Deterministic Pipeline Builder
# ⚠️  DO NOT EDIT MANUALLY — re-generate from the mapping JSON instead

# COMMAND ----------
# MAGIC %md
# MAGIC # 01 — Ingest Raw Source Data into 'ingest_raw_crm'
# MAGIC Reads the primary_source extract and writes unmodified data (plus audit columns) into 'ingest_raw_crm'.
# MAGIC
# MAGIC > Generated by DPBA. Source: mapping JSON → PipelineSpec → Component 3.


# COMMAND ----------
import pyspark.sql.functions as F
from pyspark.sql.types import StructType, StructField, StringType
from datetime import datetime

# COMMAND ----------
# ── Parameters ──────────────────────────────────────────────────────────
dbutils.widgets.text("source_path", "/mnt/raw/crm_customers/", "Source Path")
dbutils.widgets.text("ingest_raw_crm_table", "main.ingest_raw_crm.raw_crm_customers", "Ingest_Raw_Crm Table")
dbutils.widgets.text("run_date",    datetime.now().strftime("%Y-%m-%d"), "Run Date")
dbutils.widgets.text("synthetic_input_table", "", "Synthetic input table (test runs only)")
dbutils.widgets.text("test_mode", "false", "Reset output table for isolated tests")

SOURCE_PATH = dbutils.widgets.get("source_path")
TARGET_TABLE = dbutils.widgets.get("ingest_raw_crm_table")
RUN_DATE    = dbutils.widgets.get("run_date")
SYNTHETIC_INPUT_TABLE = dbutils.widgets.get("synthetic_input_table").strip()
TEST_MODE = dbutils.widgets.get("test_mode").lower() == "true"

print(f"[ingest_raw_crm] source  : {SOURCE_PATH}")
print(f"[ingest_raw_crm] table   : {TARGET_TABLE}")
print(f"[ingest_raw_crm] run_date: {RUN_DATE}")

# COMMAND ----------
# ── Raw schema (all string — avoid parse failures on ingest) ─────────────
RAW_SCHEMA = StructType([
    StructField("cust_id", StringType(), True),
    StructField("fname", StringType(), True),
    StructField("lname", StringType(), True),
    StructField("signup_dt_raw", StringType(), True),
    StructField("bal_cents_raw", StringType(), True),
    StructField("active_flag_raw", StringType(), True),
    StructField("acct_close_dt_raw", StringType(), True),
])

# COMMAND ----------
# ── Read (source_configuration: format="csv") ───────────
if SYNTHETIC_INPUT_TABLE:
    df_raw = spark.read.table(SYNTHETIC_INPUT_TABLE).select(*RAW_SCHEMA.fieldNames(), F.col("_tc_id"))
else:
    df_raw = (
    spark.read
    .format("csv")
    .option("header", "true")
        .option("inferSchema", "false")
    .schema(RAW_SCHEMA)
    .load(SOURCE_PATH)
)
raw_count = df_raw.count()
print(f"[ingest_raw_crm] Raw rows read: {raw_count}")

# COMMAND ----------
# ── Audit columns (carried through every downstream stage) ───────────────
df_out = (
    df_raw
    .withColumn("_ingested_at", F.current_timestamp())
    .withColumn("_source_file", F.input_file_name())
    .withColumn("_run_date",    F.lit(RUN_DATE))
)
if TEST_MODE and SYNTHETIC_INPUT_TABLE:
    df_out = df_out.withColumn("_tc_id", F.col("_tc_id"))

# COMMAND ----------
# ── Ensure the target schema exists (the catalog itself must already exist —
# ── creating a catalog needs metastore-admin privileges this notebook doesn't assume) ──
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {'.'.join(TARGET_TABLE.split('.')[:2])}")

# ── Write ─────────────────────────────────────────────────────────────
(
    df_out
    .write.format("delta").mode("overwrite" if TEST_MODE else "append")
    .option("mergeSchema", "true")
    .saveAsTable(TARGET_TABLE)
)
out_count = df_out.count()
print(f"[ingest_raw_crm] ✅ Wrote {out_count} rows to {TARGET_TABLE}")

# COMMAND ----------
import json
dbutils.notebook.exit(json.dumps({"status": "SUCCESS", "raw_count": raw_count, "ingest_raw_crm_count": out_count}))
