# Databricks notebook source
# Auto-generated by DPBA — Component 3: Deterministic Pipeline Builder
# ⚠️  DO NOT EDIT MANUALLY — re-generate from the mapping JSON instead

# COMMAND ----------
# MAGIC %md
# MAGIC # 02 — Transform 'ingest_raw_crm' → 'transform_customer_dim'
# MAGIC Applies all mapping transformations, enforces data_expectations, and writes 'transform_customer_dim'.
# MAGIC
# MAGIC > Generated by DPBA. Source: mapping JSON → PipelineSpec → Component 3.


# COMMAND ----------
import pyspark.sql.functions as F
from pyspark.sql.types import (
    StringType, DecimalType, BooleanType, DateType, IntegerType, LongType, DoubleType, TimestampType
)
from pyspark.sql.window import Window
from delta.tables import DeltaTable
from datetime import datetime
import json

# COMMAND ----------
# ── Parameters ──────────────────────────────────────────────────────────
dbutils.widgets.text("ingest_raw_crm_table", "main.ingest_raw_crm.raw_crm_customers", "Ingest_Raw_Crm Table")
dbutils.widgets.text("transform_customer_dim_table", "main.transform_customer_dim.dim_customers",      "Transform_Customer_Dim Table")
dbutils.widgets.text("run_date",       datetime.now().strftime("%Y-%m-%d"), "Run Date")
dbutils.widgets.text("write_mode",     "append", "Write Mode (ignored when merge_keys are set)")
dbutils.widgets.text("quarantine_table", "main.transform_customer_dim.dim_customers_quarantine", "Quarantine Table")
dbutils.widgets.text("test_mode", "false", "Reset outputs for isolated integration tests")

SOURCE_TABLE = dbutils.widgets.get("ingest_raw_crm_table")
TARGET_TABLE = dbutils.widgets.get("transform_customer_dim_table")
RUN_DATE     = dbutils.widgets.get("run_date")
WRITE_MODE   = dbutils.widgets.get("write_mode")
QUARANTINE_TABLE = dbutils.widgets.get("quarantine_table")
TEST_MODE = dbutils.widgets.get("test_mode").lower() == "true"

# COMMAND ----------
# ── Ensure the target schema exists before anything writes to it (TARGET_TABLE
# ── and QUARANTINE_TABLE share the same schema) — the catalog itself must
# ── already exist; creating a catalog needs metastore-admin privileges this
# ── notebook doesn't assume.
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {'.'.join(TARGET_TABLE.split('.')[:2])}")
if TEST_MODE and spark.catalog.tableExists(TARGET_TABLE):
    DeltaTable.forName(spark, TARGET_TABLE).delete()
if TEST_MODE and spark.catalog.tableExists(QUARANTINE_TABLE):
    DeltaTable.forName(spark, QUARANTINE_TABLE).delete()

# COMMAND ----------
# ── Read 'ingest_raw_crm' ──────────────────────────────────────────────
df = spark.read.table(SOURCE_TABLE).filter(F.col("_run_date") == RUN_DATE)
source_count = df.count()
print(f"[transform_customer_dim] 'ingest_raw_crm' rows for {RUN_DATE}: {source_count}")

# COMMAND ----------
# ── Transformations (auto-generated from this stage's mappings[]) ────────
# ── customer_id ──────────
# Rule: cast cust_id → customer_id (string)
df = df.withColumn("customer_id", F.trim(F.col("cust_id").cast(StringType())))
df = df.withColumn("customer_id", F.col("customer_id").cast(StringType()))
# ── full_name ──────────
# Rule: concat fname + lname → full_name
df = df.withColumn(
    "full_name",
    F.when(F.col("fname").isNull() & F.col("lname").isNull(), F.lit(None).cast(StringType()))
     .otherwise(F.concat_ws(" ", F.trim(F.col("fname").cast(StringType())), F.trim(F.col("lname").cast(StringType()))))
)
df = df.withColumn("full_name", F.col("full_name").cast(StringType()))
# ── signup_date ──────────
# Rule: signup_dt_raw → signup_date (date; sentinel "None" → NULL)
df = df.withColumn(
    "signup_date",
    F.when(F.lit(False), F.lit(None).cast(DateType()))
     .otherwise(F.coalesce(
            F.to_date(F.col("signup_dt_raw"), "yyyyMMdd"),
            F.to_date(F.col("signup_dt_raw"), "yyyy-MM-dd"),
            F.to_date(F.col("signup_dt_raw"), "MM/dd/yyyy"),
            F.lit(None).cast(DateType())
        ))
)
df = df.withColumn("signup_date", F.col("signup_date").cast(DateType()))
# ── account_balance ──────────
# Rule: bal_cents_raw → account_balance (conditional numeric scale, ÷1)
df = df.withColumn(
    "account_balance",
    F.when(F.col("bal_cents_raw").cast(DecimalType(18, 2)).isNotNull(),
           (F.col("bal_cents_raw").cast(DecimalType(18, 2)) / F.lit(1)).cast(DecimalType(18, 2)))
     .otherwise(F.lit(None).cast(DecimalType(18, 2)))
)
df = df.withColumn("account_balance", F.col("account_balance").cast(DecimalType(18, 2)))
# ── is_active ──────────
# Rule: active_flag_raw → is_active (lookup: {'Y': True, 'N': False, 'y': True, 'n': False})
df = df.withColumn(
    "is_active",
    F.when(F.col("active_flag_raw").isNull(), F.lit(None).cast(BooleanType()))
     .when(F.upper(F.trim(F.col("active_flag_raw"))) == "Y", F.lit(True))
     .when(F.upper(F.trim(F.col("active_flag_raw"))) == "N", F.lit(False))
     .when(F.upper(F.trim(F.col("active_flag_raw"))) == "Y", F.lit(True))
     .when(F.upper(F.trim(F.col("active_flag_raw"))) == "N", F.lit(False))
     .otherwise(F.lit(None).cast(BooleanType()))
)
df = df.withColumn("is_active", F.col("is_active").cast(BooleanType()))
# ── account_closed_date ──────────
# Rule: acct_close_dt_raw → account_closed_date (date; sentinel "None" → NULL)
df = df.withColumn(
    "account_closed_date",
    F.when(F.lit(False), F.lit(None).cast(DateType()))
     .otherwise(F.coalesce(
            F.to_date(F.col("acct_close_dt_raw"), "yyyy-MM-dd"),
            F.lit(None).cast(DateType())
        ))
)
df = df.withColumn("account_closed_date", F.col("account_closed_date").cast(DateType()))

# COMMAND ----------
# ── Data expectations: fail_pipeline (checked first — halts before any write) ─
# (no fail_pipeline expectations)

# COMMAND ----------
# ── Data expectations: quarantine (violating rows routed to a separate table) ─
_q_parts = []
# Expectation "customer_id_not_null" (quarantine): customer_id IS_NOT_NULL
_mask = (~(F.col("customer_id").isNotNull())) | (F.col("customer_id").isNotNull()).isNull()
_q_parts.append(df.filter(_mask).withColumn("_quarantine_reason", F.lit("customer_id_not_null")))
df = df.filter(~_mask)

if _q_parts:
    df_quarantine = _q_parts[0]
    for _part in _q_parts[1:]:
        df_quarantine = df_quarantine.unionByName(_part)
    quarantine_count = df_quarantine.count()
    print(f"[transform_customer_dim] ⚠️  {quarantine_count} row(s) quarantined")
    (
        df_quarantine
        .withColumn("_quarantined_at", F.current_timestamp())
        .write.format("delta").mode("append").option("mergeSchema", "true")
        .saveAsTable(QUARANTINE_TABLE)
    )
else:
    quarantine_count = 0

# COMMAND ----------
# ── Data expectations: drop_row (violating rows silently removed) ────────────
# Expectation "account_balance_non_negative" (drop_row): account_balance >=
_mask = (~(F.col("account_balance") >= 0.0)) | (F.col("account_balance") >= 0.0).isNull()
_dropped = df.filter(_mask).count()
if _dropped > 0:
    print(f"[silver] ℹ️  Dropped {_dropped} row(s) failing 'account_balance_non_negative' (action_on_failure=drop_row)")
df = df.filter(~_mask)

# COMMAND ----------
# ── Data expectations outside the supported rule grammar ─────────────────────
# (no unparsed expectations)

# COMMAND ----------
# ── Deduplicate within this batch (required before MERGE; also protects append) ─
# No merge_keys declared for this stage — appending rows as-is (no forced dedup key).
dedup_count = source_count - quarantine_count - df.count()

# COMMAND ----------
# ── Select this stage's final columns (+ audit columns, carried forward) ──
_output_columns = ['customer_id', 'full_name', 'signup_date', 'account_balance', 'is_active', 'account_closed_date'] + ["_ingested_at", "_source_file", "_run_date"]
if TEST_MODE and "_tc_id" in df.columns:
    _output_columns.append("_tc_id")
df_out = df.select(*_output_columns)

# COMMAND ----------
# ── Write (append, no merge_keys declared for this stage) ────────────────
(
    df_out
    .write.format("delta").mode(WRITE_MODE)
    .option("mergeSchema", "true")
    .partitionBy("_run_date")
    .saveAsTable(TARGET_TABLE)
)
out_count = df_out.count()
print(f"[transform_customer_dim] ✅ Wrote/merged {out_count} rows into {TARGET_TABLE}")

# COMMAND ----------
dbutils.notebook.exit(json.dumps({
    "status": "SUCCESS", "ingest_raw_crm_count": source_count,
    "transform_customer_dim_count": out_count, "quarantine_count": quarantine_count,
}))
