# Databricks notebook source
# Auto-generated by DPBA — Component 3: Deterministic Pipeline Builder
# ⚠️  DO NOT EDIT MANUALLY — re-generate from the mapping JSON instead

# COMMAND ----------
# MAGIC %md
# MAGIC # 03 — Integration Tests
# MAGIC Loads Component 2's test fixtures from Unity Catalog and validates 'transform_customer_dim' + quarantine table output.
# MAGIC
# MAGIC > Generated by DPBA. Source: mapping JSON → PipelineSpec → Component 3.


# COMMAND ----------
import json
import pyspark.sql.functions as F
from pyspark.sql.types import *
from datetime import datetime

# COMMAND ----------
# ── Parameters ──────────────────────────────────────────────────────────
dbutils.widgets.text("transform_customer_dim_table",            "main.transform_customer_dim.dim_customers", "Transform_Customer_Dim Table")
dbutils.widgets.text("run_date",                 datetime.now().strftime("%Y-%m-%d"), "Run Date")
dbutils.widgets.text("synthetic_input_table",    "main.transform_customer_dim_test.transform_customer_dim_synthetic_input", "Synthetic Input Table")
dbutils.widgets.text("expected_output_table",    "main.transform_customer_dim_test.transform_customer_dim_expected_output", "Expected Output Table")
dbutils.widgets.text("quarantine_table", "main.transform_customer_dim.dim_customers_quarantine", "Quarantine Table")


FINAL_TABLE           = dbutils.widgets.get("transform_customer_dim_table")
RUN_DATE              = dbutils.widgets.get("run_date")
SYNTHETIC_INPUT_TABLE = dbutils.widgets.get("synthetic_input_table")
EXPECTED_OUTPUT_TABLE = dbutils.widgets.get("expected_output_table")
QUARANTINE_TABLE      = dbutils.widgets.get("quarantine_table")


# COMMAND ----------
# ── Load test fixtures from Unity Catalog (written by 00_load_test_fixtures) ──
total_cases = spark.read.table(SYNTHETIC_INPUT_TABLE).count()
input_rows = [r.asDict() for r in spark.read.table(SYNTHETIC_INPUT_TABLE).collect()]
expected_rows = [r.asDict() for r in spark.read.table(EXPECTED_OUTPUT_TABLE).collect()]
expected_by_id = {row["_tc_id"]: row for row in expected_rows}
print(f"[test] {total_cases} total test cases in {SYNTHETIC_INPUT_TABLE} "
      f"({len(expected_rows)} expected in 'transform_customer_dim')")

# COMMAND ----------
# ── Load final-stage output ───────────────────────────────────────────────
df_final = spark.read.table(FINAL_TABLE).filter(F.col("_run_date") == RUN_DATE)
df_quarantine = spark.read.table(QUARANTINE_TABLE) if spark.catalog.tableExists(QUARANTINE_TABLE) else None

# ── Test runner ──────────────────────────────────────────────────────────
results   = []
failures  = []

def assert_test(tc_id, description, condition, detail=""):
    entry = {"tc_id": tc_id, "description": description,
              "status": "PASS" if condition else "FAIL", "detail": detail}
    results.append(entry)
    if not condition:
        failures.append(entry)
        print(f"  ❌ [{tc_id}] {description}: {detail}")
    else:
        print(f"  ✅ [{tc_id}] {description}")

# COMMAND ----------
# ── Schema validation (derived from mappings[], not hardcoded) ───────────
EXPECTED_SCHEMA = {
    "customer_id": "string",
    "full_name": "string",
    "signup_date": "date",
    "account_balance": "decimal(18,2)",
    "is_active": "boolean",
    "account_closed_date": "date"
}
actual_types = {f.name: f.dataType.simpleString() for f in df_final.schema.fields}
for col_name, expected_type in EXPECTED_SCHEMA.items():
    assert_test(
        f"SCH-{col_name}", f"Column '{col_name}' has type '{expected_type}'",
        actual_types.get(col_name) == expected_type,
        f"Got '{actual_types.get(col_name)}'"
    )

# COMMAND ----------
# ── Per-test-case value assertions ───────────────────────────────────────
print("\n--- Value Assertions ---")
PK_TARGET = "customer_id"
expected_types = {'customer_id': 'string', 'full_name': 'string', 'signup_date': 'date', 'account_balance': 'decimal(18,2)', 'is_active': 'boolean', 'account_closed_date': 'date'}
def values_equal(actual, expected, target_type):
    if expected is None:
        return actual is None
    if target_type.startswith("decimal("):
        from decimal import Decimal
        return Decimal(str(actual)) == Decimal(str(expected))
    if target_type in ("int", "integer", "long"):
        return int(actual) == int(expected)
    if target_type in ("bool", "boolean"):
        return str(actual).lower() == str(expected).lower()
    return str(actual) == str(expected)

actual_by_id = {}
for actual_row in df_final.collect():
    actual_by_id.setdefault(actual_row["_tc_id"], []).append(actual_row)
quarantined_by_id = {}
if df_quarantine is not None:
    for quarantine_row in df_quarantine.filter(F.col("_run_date") == RUN_DATE).collect():
        quarantined_by_id.setdefault(quarantine_row["_tc_id"], []).append(quarantine_row)
for case in input_rows:
    tc_id = case["_tc_id"]
    disposition = case["_expected_disposition"]
    if disposition == "silver":
        rows = actual_by_id.get(tc_id, [])
        row = rows[0] if rows else None
        assert_test(tc_id, "Expected exactly one final output row", len(rows) == 1,
                    f"Found {len(rows)} output rows")
        expected = expected_by_id.get(tc_id)
        if row is not None and expected is not None:
            for col, expected_value in expected.items():
                if col in ('_tc_id', '_scenario', '_edge_case'):
                    continue
                actual = row[col]
                assert_test(tc_id, f"{col} matches expected value", values_equal(actual, expected_value, expected_types[col]),
                            f"Expected {expected_value!r}, got {actual!r}")
    elif disposition == "quarantine":
        rows = quarantined_by_id.get(tc_id, [])
        assert_test(tc_id, "Expected exactly one quarantined row", len(rows) == 1,
                    f"Found {len(rows)} quarantined rows")
    elif disposition == "dropped":
        assert_test(tc_id, "Expected row dropped", tc_id not in actual_by_id and tc_id not in quarantined_by_id,
                    "Dropped case appeared in final or quarantine output")
    else:
        assert_test(tc_id, "Known expected disposition", False, f"Unsupported disposition {disposition!r}")

expected_silver_ids = set(expected_by_id)
assert_test("ALL-SILVER", "No unexpected final output rows", set(actual_by_id) == expected_silver_ids and all(len(rows) == 1 for rows in actual_by_id.values()),
            f"Unexpected IDs: {sorted(set(actual_by_id) - expected_silver_ids)}")
expected_quarantine_ids = {row["_tc_id"] for row in input_rows if row["_expected_disposition"] == "quarantine"}
assert_test("ALL-QUARANTINE", "All and only expected rows are quarantined", set(quarantined_by_id) == expected_quarantine_ids and all(len(rows) == 1 for rows in quarantined_by_id.values()),
            f"Unexpected quarantine IDs: {sorted(set(quarantined_by_id) ^ expected_quarantine_ids)}")

# COMMAND ----------
# ── Declarative data-expectation checks (drop_row / quarantine) ──────────
print("\n--- Data Expectation Checks ---")
_viol = df_final.filter((~(F.col("customer_id").isNotNull())) | (F.col("customer_id").isNotNull()).isNull()).count()
assert_test("EXP-customer_id_not_null", "No transform_customer_dim rows violate 'customer_id IS_NOT_NULL' (quarantine)",
            _viol == 0, f"{_viol} violating row(s) still in transform_customer_dim")

_viol = df_final.filter((~(F.col("account_balance") >= 0.0)) | (F.col("account_balance") >= 0.0).isNull()).count()
assert_test("EXP-account_balance_non_negative", "No transform_customer_dim rows violate 'account_balance >=' (drop_row)",
            _viol == 0, f"{_viol} violating row(s) still in transform_customer_dim")

# COMMAND ----------
# ── fail_pipeline expectations — documented, not re-tested in this batch ──
print("  (no fail_pipeline expectations)")

# COMMAND ----------
# ── Intermediate-stage row-count sanity checks ────────────────────────────
print("\n--- Intermediate Stage Checks ---")
# (no intermediate stages between ingest and the final stage)

# COMMAND ----------
# ── Summary ──────────────────────────────────────────────────────────────
total  = len(results)
passed = sum(1 for r in results if r["status"] == "PASS")
failed = total - passed
print(f"\n============================================================")
print(f"  TEST SUMMARY: {passed}/{total} passed, {failed} failed")
print(f"============================================================")

exit_payload = json.dumps({
    "status":       "SUCCESS" if failed == 0 else "FAILURE",
    "total_tests":  total, "passed": passed, "failed": failed,
    "failed_tests": [r["tc_id"] for r in failures],
})

if failed > 0:
    raise Exception(f"Integration tests FAILED:\n{exit_payload}")
else:
    dbutils.notebook.exit(exit_payload)
