"""
DPBA — Component 3: Deterministic Pipeline Builder (Tool)
==========================================================
Converts a PipelineSpec (parsed from the canonical universal mapping JSON)
into production-ready, auditable Databricks pipeline code. No AI involved —
the same spec always produces the same output.

NOT hardcoded to a fixed bronze→silver medallion shape: the pipeline is an
arbitrary, JSON-declared CHAIN of stages (spec.stages — see mapping_parser).
This module generates one notebook per stage transition, however many stages
the mapping JSON declares (2 for a simple ingest→silver pipeline, 3 for a
classic bronze→silver→gold medallion, N for anything else), plus one final
integration-test notebook, wired into a dynamically-built DAB job DAG:

  notebooks/00_load_test_fixtures.py      — Writes Component 2's generated test
                                             suite into Unity Catalog as real
                                             Delta tables (content generated by
                                             Component 2 — see
                                             component2_data_generator.generate_load_fixtures_notebook —
                                             Component 3 just assembles it in).
  notebooks/01_ingest_<stage0>.py         — Raw source → stages[0] (straight copy)
  notebooks/0{i}_transform_<stageN>.py    — stages[i-1] → stages[i]: field
                                             transforms, data-expectation
                                             enforcement (drop_row / quarantine /
                                             fail_pipeline), dedup, and a real
                                             Delta MERGE upsert when that
                                             stage declares merge_keys.
                                             (repeated once per transform stage)
  notebooks/0{N+1}_integration_tests.py   — Schema + per-test-case value
                                             assertions against the FINAL
                                             stage, read from the Unity
                                             Catalog fixture tables above, plus
                                             row-count sanity checks on any
                                             intermediate stages.
  resources/pipeline_job.yml              — DAB job YAML; one task per stage
                                             transition, chained via depends_on
                                             in stage order, cluster spec
                                             pulled from workflow_specification.
  databricks.yml                          — DAB root bundle config (from
                                             bundle_metadata / target_environments)

Architecture: every PySpark snippet is dispatched purely from a field's
*explicit* `transformation_type` (never from parsing `transformation_logic`,
which is a human-readable comment only) — this is what the hackathon spec
means by "deterministic... no AI guessing" in Component 3. An unsupported or
missing type is a loud build-time error, not a silent best-effort guess.
"""

from __future__ import annotations

import os
import re
import sys
import textwrap
from typing import Any, Optional

from mapping_parser import (
    FieldMapping, PipelineSpec, PipelineStage, DataExpectation, parse_mapping_json, print_spec_table,
    parse_expectation_rule,
    T_DIRECT, T_CAST, T_CONCAT, T_CONDITIONAL, T_DATE_FORMAT, T_CONDITIONAL_DATE,
    T_LOOKUP, T_SPLIT,
)
# Notebook CONTENT generation for the Unity Catalog test-fixture loader lives
# in Component 2 (it owns the test data); Component 3 just assembles the
# result into the final deployable bundle, same as its own notebooks.
from component2_data_generator import generate_load_fixtures_notebook


# ─────────────────────────────────────────────────────────────────────────────
# Literal rendering helpers
# ─────────────────────────────────────────────────────────────────────────────

def _python_literal(value: Any) -> str:
    """Render a JSON value as a safe Python/PySpark literal."""
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, (int, float)):
        return repr(value)
    return '"' + str(value).replace('\\', '\\\\').replace('"', '\\"') + '"'


def _reindent(block: str, indent: str = "        ") -> str:
    """Re-indent a multi-line code block so every line after the first carries
    `indent` — needed because f-string substitution only places the *first*
    line of a value at the surrounding template's column; continuation lines
    are inserted verbatim and must be prefixed explicitly or the generated
    notebook ends up with inconsistent (invalid) Python indentation."""
    return f"\n{indent}".join(block.split("\n"))


def _apply_default(fm: FieldMapping, snippet: str) -> str:
    """Universal default-value substitution, applied uniformly after every
    transformation type: if default_value is set, coalesce the computed
    (possibly null) result with it. Kept as one shared pass rather than
    duplicated per-type logic, so every type gets identical default semantics."""
    if fm.default_value is None:
        return snippet
    default_literal = _python_literal(fm.default_value)
    return (
        f'{snippet}\n'
        f'df = df.withColumn(\n'
        f'    "{fm.target_field}",\n'
        f'    F.coalesce(F.col("{fm.target_field}"), F.lit({default_literal}).cast({fm.spark_type_literal}))\n'
        f')'
    )


# ─────────────────────────────────────────────────────────────────────────────
# PySpark snippet library — one function per transformation_type
# ─────────────────────────────────────────────────────────────────────────────

class SnippetLibrary:

    @staticmethod
    def direct(fm: FieldMapping) -> str:
        if not fm.source_fields:
            return (
                f'# {fm.target_field} — transformation.type=direct, no source_fields → always NULL\n'
                f'df = df.withColumn("{fm.target_field}", F.lit(None).cast({fm.spark_type_literal}))'
            )
        src = fm.primary_source
        return (
            f'# Rule: {src} → {fm.target_field} (direct passthrough)\n'
            f'df = df.withColumn("{fm.target_field}", F.col("{src}").cast({fm.spark_type_literal}))'
        )

    @staticmethod
    def cast(fm: FieldMapping) -> str:
        src = fm.primary_source
        expr = f'F.col("{src}").cast({fm.spark_type_literal})'
        if fm.spark_type_literal == "StringType()":
            expr = f'F.trim({expr})'
        if fm.transformation_params.get("uppercase"):
            expr = f'F.upper({expr})'
        elif fm.transformation_params.get("lowercase"):
            expr = f'F.lower({expr})'
        return (
            f'# Rule: cast {src} → {fm.target_field} ({fm.target_data_type})\n'
            f'df = df.withColumn("{fm.target_field}", {expr})'
        )

    @staticmethod
    def concat(fm: FieldMapping) -> str:
        sep = fm.transformation_params.get("separator", " ")
        cols = ", ".join(f'F.trim(F.col("{s}").cast(StringType()))' for s in fm.source_fields)
        null_check = " & ".join(f'F.col("{s}").isNull()' for s in fm.source_fields)
        src_label = " + ".join(fm.source_fields)
        return (
            f'# Rule: concat {src_label} → {fm.target_field}\n'
            f'df = df.withColumn(\n'
            f'    "{fm.target_field}",\n'
            f'    F.when({null_check}, F.lit(None).cast(StringType()))\n'
            f'     .otherwise(F.concat_ws("{sep}", {cols}))\n'
            f')'
        )

    @staticmethod
    def conditional(fm: FieldMapping) -> str:
        """Numeric scale transform: value / divisor when present, else null
        (default_value substitution happens in the universal _apply_default pass)."""
        src = fm.primary_source
        divisor = fm.transformation_params.get("divisor")
        if divisor is None:
            m = re.search(r"/\s*(\d+)", fm.transformation_logic)
            divisor = int(m.group(1)) if m else (100 if "cent" in fm.transformation_logic.lower() else 1)
        spark_type = fm.spark_type_literal
        return (
            f'# Rule: {src} → {fm.target_field} (conditional numeric scale, ÷{divisor})\n'
            f'df = df.withColumn(\n'
            f'    "{fm.target_field}",\n'
            f'    F.when(F.col("{src}").cast({spark_type}).isNotNull(),\n'
            f'           F.col("{src}").cast({spark_type}) / F.lit({divisor}))\n'
            f'     .otherwise(F.lit(None).cast({spark_type}))\n'
            f')'
        )

    @staticmethod
    def date_format(fm: FieldMapping) -> str:
        src = fm.primary_source
        params = fm.transformation_params
        source_formats = params.get("source_formats") or ["yyyyMMdd", "yyyy/MM/dd", "yyyy-MM-dd", "MM/dd/yyyy"]
        output_format = params.get("output_format")
        fmt_lines = ",\n".join(f'        F.to_date(F.col("{src}"), "{fmt}")' for fmt in source_formats)
        parsed_expr = f'F.coalesce(\n{fmt_lines},\n        F.lit(None).cast(DateType())\n    )'
        if output_format:
            return (
                f'# Rule: {src} → {fm.target_field} (date, formats {source_formats} → "{output_format}")\n'
                f'df = df.withColumn("{fm.target_field}", F.date_format({parsed_expr}, "{output_format}"))'
            )
        return (
            f'# Rule: {src} → {fm.target_field} (date, multi-format: {source_formats})\n'
            f'df = df.withColumn("{fm.target_field}", {parsed_expr})'
        )

    @staticmethod
    def conditional_date(fm: FieldMapping) -> str:
        src = fm.primary_source
        params = fm.transformation_params
        sentinel = params.get("sentinel_value")
        source_formats = params.get("source_formats") or ["yyyy-MM-dd", "yyyyMMdd", "MM/dd/yyyy"]
        output_format = params.get("output_format")
        fmt_lines = ",\n".join(f'            F.to_date(F.col("{src}"), "{fmt}")' for fmt in source_formats)
        parsed_expr = f'F.coalesce(\n{fmt_lines},\n            F.lit(None).cast(DateType())\n        )'
        value_expr = f'F.date_format({parsed_expr}, "{output_format}")' if output_format else parsed_expr
        null_type = "StringType()" if output_format else "DateType()"
        sentinel_check = f'F.trim(F.col("{src}")) == "{sentinel}"' if sentinel else "F.lit(False)"
        return (
            f'# Rule: {src} → {fm.target_field} (date; sentinel "{sentinel}" → NULL)\n'
            f'df = df.withColumn(\n'
            f'    "{fm.target_field}",\n'
            f'    F.when({sentinel_check}, F.lit(None).cast({null_type}))\n'
            f'     .otherwise({value_expr})\n'
            f')'
        )

    @staticmethod
    def lookup(fm: FieldMapping) -> str:
        src = fm.primary_source
        params = fm.transformation_params
        value_map: dict = params.get("value_map", {})
        case_insensitive = params.get("case_insensitive", True)
        col_expr = f'F.trim(F.col("{src}"))'
        if case_insensitive:
            col_expr = f'F.upper({col_expr})'
        when_lines = []
        for k, v in value_map.items():
            key = str(k).upper() if case_insensitive else str(k)
            when_lines.append(f'     .when({col_expr} == "{key}", F.lit({_python_literal(v)}))')
        when_str = "\n".join(when_lines)
        return (
            f'# Rule: {src} → {fm.target_field} (lookup: {value_map})\n'
            f'df = df.withColumn(\n'
            f'    "{fm.target_field}",\n'
            f'    F.when(F.col("{src}").isNull(), F.lit(None).cast({fm.spark_type_literal}))\n'
            f'{when_str}\n'
            f'     .otherwise(F.lit(None).cast({fm.spark_type_literal}))\n'
            f')'
        )

    @staticmethod
    def split(fm: FieldMapping) -> str:
        src = fm.primary_source
        params = fm.transformation_params
        delimiter = params.get("delimiter", " ")
        index = int(params.get("index", 0))
        return (
            f'# Rule: {src} → {fm.target_field} (split on "{delimiter}", index {index})\n'
            f'df = df.withColumn(\n'
            f'    "{fm.target_field}",\n'
            f'    F.trim(F.split(F.col("{src}"), "{re.escape(delimiter)}").getItem({index}))\n'
            f')'
        )


_DISPATCH = {
    T_DIRECT: SnippetLibrary.direct,
    T_CAST: SnippetLibrary.cast,
    T_CONCAT: SnippetLibrary.concat,
    T_CONDITIONAL: SnippetLibrary.conditional,
    T_DATE_FORMAT: SnippetLibrary.date_format,
    T_CONDITIONAL_DATE: SnippetLibrary.conditional_date,
    T_LOOKUP: SnippetLibrary.lookup,
    T_SPLIT: SnippetLibrary.split,
}


def _get_snippet(fm: FieldMapping) -> str:
    fn = _DISPATCH.get(fm.transformation_type)
    if fn is None:
        raise ValueError(f"No codegen for transformation.type={fm.transformation_type!r} (field {fm.target_field!r})")
    return _apply_default(fm, fn(fm))


# ─────────────────────────────────────────────────────────────────────────────
# Data-expectation → Spark condition
# ─────────────────────────────────────────────────────────────────────────────

def _spark_condition(parsed: dict) -> str:
    """Spark boolean Column expression STRING for the rule being satisfied."""
    target_field, op, value = parsed["field"], parsed["op"], parsed["value"]
    col = f'F.col("{target_field}")'
    return {
        "IS NOT NULL": f'{col}.isNotNull()',
        "IS NULL":     f'{col}.isNull()',
        ">=": f'{col} >= {value}',
        "<=": f'{col} <= {value}',
        ">":  f'{col} > {value}',
        "<":  f'{col} < {value}',
        "==": f'{col} == {value}',
        "=":  f'{col} == {value}',
        "!=": f'{col} != {value}',
    }[op]


# ─────────────────────────────────────────────────────────────────────────────
# Notebook generators
# ─────────────────────────────────────────────────────────────────────────────

def _notebook_header(title: str, description: str) -> str:
    return textwrap.dedent(f"""\
        # Databricks notebook source
        # Auto-generated by DPBA — Component 3: Deterministic Pipeline Builder
        # ⚠️  DO NOT EDIT MANUALLY — re-generate from the mapping JSON instead

        # COMMAND ----------
        # MAGIC %md
        # MAGIC # {title}
        # MAGIC {description}
        # MAGIC
        # MAGIC > Generated by DPBA. Source: mapping JSON → PipelineSpec → Component 3.
    """)


def generate_ingest_notebook(spec: PipelineSpec) -> str:
    """Raw source → stages[0] (the ingest stage, whatever it's named). Straight
    copy plus audit columns, deliberately with NO quarantine/validation logic —
    data_expectations[] operate on *target* (post-transformation) fields, so
    all enforcement lives in the transform stages, not here."""
    stage = spec.ingest_stage
    param_name = f"{stage.name}_table"

    raw_schema_fields = "\n".join(
        f'    StructField("{src}", StringType(), True),'
        for src in spec.raw_source_columns
    )
    read_options = "\n".join(
        f'    .option("{k}", "{v}")' for k, v in spec.source_read_options.items()
    )

    return textwrap.dedent(f"""\
        {_reindent(_notebook_header(
            f"01 — Ingest Raw Source Data into '{stage.name}'",
            f"Reads the {spec.source_system} extract and writes unmodified data (plus audit columns) into '{stage.name}'."
        ))}

        # COMMAND ----------
        import pyspark.sql.functions as F
        from pyspark.sql.types import StructType, StructField, StringType
        from datetime import datetime

        # COMMAND ----------
        # ── Parameters ──────────────────────────────────────────────────────────
        dbutils.widgets.text("source_path", "{spec.source_location}", "Source Path")
        dbutils.widgets.text("{param_name}", "{stage.full_table}", "{stage.name.title()} Table")
        dbutils.widgets.text("run_date",    datetime.now().strftime("%Y-%m-%d"), "Run Date")

        SOURCE_PATH = dbutils.widgets.get("source_path")
        TARGET_TABLE = dbutils.widgets.get("{param_name}")
        RUN_DATE    = dbutils.widgets.get("run_date")

        print(f"[{stage.name}] source  : {{SOURCE_PATH}}")
        print(f"[{stage.name}] table   : {{TARGET_TABLE}}")
        print(f"[{stage.name}] run_date: {{RUN_DATE}}")

        # COMMAND ----------
        # ── Raw schema (all string — avoid parse failures on ingest) ─────────────
        RAW_SCHEMA = StructType([
        {_reindent(raw_schema_fields)}
        ])

        # COMMAND ----------
        # ── Read (source_configuration: format="{spec.source_format}") ───────────
        df_raw = (
            spark.read
            .format("{spec.source_format}")
        {_reindent(read_options)}
            .schema(RAW_SCHEMA)
            .load(SOURCE_PATH)
        )
        raw_count = df_raw.count()
        print(f"[{stage.name}] Raw rows read: {{raw_count}}")

        # COMMAND ----------
        # ── Audit columns (carried through every downstream stage) ───────────────
        df_out = (
            df_raw
            .withColumn("_ingested_at", F.current_timestamp())
            .withColumn("_source_file", F.input_file_name())
            .withColumn("_run_date",    F.lit(RUN_DATE))
        )

        # COMMAND ----------
        # ── Ensure the target schema exists (the catalog itself must already exist —
        # ── creating a catalog needs metastore-admin privileges this notebook doesn't assume) ──
        spark.sql(f"CREATE SCHEMA IF NOT EXISTS {{'.'.join(TARGET_TABLE.split('.')[:2])}}")

        # ── Write ─────────────────────────────────────────────────────────────
        (
            df_out
            .write.format("{stage.format}").mode("{stage.write_mode}")
            .option("mergeSchema", "true")
            .saveAsTable(TARGET_TABLE)
        )
        out_count = df_out.count()
        print(f"[{stage.name}] ✅ Wrote {{out_count}} rows to {{TARGET_TABLE}}")

        # COMMAND ----------
        import json
        dbutils.notebook.exit(json.dumps({{"status": "SUCCESS", "raw_count": raw_count, "{stage.name}_count": out_count}}))
    """)


def generate_transform_notebook(spec: PipelineSpec, stage_index: int) -> str:
    """stages[stage_index - 1] → stages[stage_index]. Works identically whether
    this is the only transform stage (ingest→silver) or one hop in a longer
    chain (e.g. silver→gold) — the previous/current stage are read from the
    spec, nothing about "bronze"/"silver" is hardcoded."""
    stage = spec.stages[stage_index]
    prev_stage = spec.stages[stage_index - 1]
    all_target_cols = stage.all_target_fields
    notebook_num = stage_index + 1

    transformation_blocks = []
    for fm in stage.fields:
        transformation_blocks.append(f"# ── {fm.target_field} ──────────")
        transformation_blocks.append(_get_snippet(fm))
    transformations_str = _reindent("\n".join(transformation_blocks))

    # ── Data expectations, grouped by action ──────────────────────────────────
    fail_exps  = [e for e in stage.expectations if e.action_on_failure == "fail_pipeline" and e.parsed]
    drop_exps  = [e for e in stage.expectations if e.action_on_failure == "drop_row" and e.parsed]
    quar_exps  = [e for e in stage.expectations if e.action_on_failure == "quarantine" and e.parsed]
    skip_exps  = [e for e in stage.expectations if not e.parsed]

    fail_blocks = []
    for e in fail_exps:
        cond = _spark_condition(e.parsed)
        fail_blocks.append(
            f'# Expectation "{e.name}" (fail_pipeline): {e.rule}\n'
            f'_violations = df.filter(~({cond})).count()\n'
            f'if _violations > 0:\n'
            f'    raise Exception(f"Data expectation \'{e.name}\' FAILED: {{_violations}} row(s) violate '
            f'\'{e.rule}\'. Pipeline halted (action_on_failure=fail_pipeline).")\n'
            f'print(f"[silver] ✅ expectation \'{e.name}\' — 0 violations")'
        )
    fail_block_str = _reindent("\n\n".join(fail_blocks) or "# (no fail_pipeline expectations)")

    quarantine_blocks = []
    for e in quar_exps:
        cond = _spark_condition(e.parsed)
        quarantine_blocks.append(
            f'# Expectation "{e.name}" (quarantine): {e.rule}\n'
            f'_mask = ~({cond})\n'
            f'_q_parts.append(df.filter(_mask).withColumn("_quarantine_reason", F.lit("{e.name}")))\n'
            f'df = df.filter(~_mask)'
        )
    quarantine_block_str = _reindent("\n\n".join(quarantine_blocks) or "# (no quarantine expectations)")

    drop_blocks = []
    for e in drop_exps:
        cond = _spark_condition(e.parsed)
        drop_blocks.append(
            f'# Expectation "{e.name}" (drop_row): {e.rule}\n'
            f'_mask = ~({cond})\n'
            f'_dropped = df.filter(_mask).count()\n'
            f'if _dropped > 0:\n'
            f'    print(f"[silver] ℹ️  Dropped {{_dropped}} row(s) failing \'{e.name}\' (action_on_failure=drop_row)")\n'
            f'df = df.filter(~_mask)'
        )
    drop_block_str = _reindent("\n\n".join(drop_blocks) or "# (no drop_row expectations)")

    skip_comment = _reindent("\n".join(
        f'# ⚠️  Expectation "{e.name}" ({e.rule!r}) is outside the supported rule grammar — '
        f'not auto-enforced. Review manually.' for e in skip_exps
    ) or "# (no unparsed expectations)")

    # ── Dedup + write (MERGE when this stage declares merge_keys, else plain append) ─
    # No merge_keys → no forced dedup key is invented; the stage just appends
    # whatever rows survive the expectation filters above.
    if stage.merge_keys:
        pk_cols_str = ", ".join(f'"{c}"' for c in stage.merge_keys)
        dedup_block = textwrap.dedent(f"""\
            _w = Window.partitionBy({pk_cols_str}).orderBy(F.col("_ingested_at").desc())
            df = (
                df.withColumn("_rn", F.row_number().over(_w))
                  .filter(F.col("_rn") == 1)
                  .drop("_rn")
            )""")
        merge_condition = " AND ".join(f't.{k} = s.{k}' for k in stage.merge_keys)
        write_block = textwrap.dedent(f"""\
            # ── Write via Delta MERGE (upsert on {stage.merge_keys}) ───────────
            if spark.catalog.tableExists(TARGET_TABLE):
                delta_target = DeltaTable.forName(spark, TARGET_TABLE)
                (
                    delta_target.alias("t")
                    .merge(df_out.alias("s"), "{merge_condition}")
                    .whenMatchedUpdateAll()
                    .whenNotMatchedInsertAll()
                    .execute()
                )
                out_count = spark.read.table(TARGET_TABLE).count()
            else:
                df_out.write.format("{stage.format}").mode("overwrite").option("mergeSchema", "true").saveAsTable(TARGET_TABLE)
                out_count = df_out.count()""")
    else:
        dedup_block = "# No merge_keys declared for this stage — appending rows as-is (no forced dedup key)."
        write_block = textwrap.dedent(f"""\
            # ── Write (append, no merge_keys declared for this stage) ────────────────
            (
                df_out
                .write.format("{stage.format}").mode(WRITE_MODE)
                .option("mergeSchema", "true")
                .partitionBy("_run_date")
                .saveAsTable(TARGET_TABLE)
            )
            out_count = df_out.count()""")

    quarantine_table = f"{stage.catalog}.{stage.schema}.{stage.table}_quarantine"
    source_param = f"{prev_stage.name}_table"
    target_param = f"{stage.name}_table"

    return textwrap.dedent(f"""\
        {_reindent(_notebook_header(
            f"{notebook_num:02d} — Transform '{prev_stage.name}' → '{stage.name}'",
            f"Applies all mapping transformations, enforces data_expectations, and writes '{stage.name}'."
        ))}

        # COMMAND ----------
        import pyspark.sql.functions as F
        from pyspark.sql.types import (
            StringType, DecimalType, BooleanType, DateType, IntegerType, LongType, DoubleType, TimestampType
        )
        from pyspark.sql.window import Window
        from delta.tables import DeltaTable
        from datetime import datetime
        import json

        # COMMAND ----------
        # ── Parameters ──────────────────────────────────────────────────────────
        dbutils.widgets.text("{source_param}", "{prev_stage.full_table}", "{prev_stage.name.title()} Table")
        dbutils.widgets.text("{target_param}", "{stage.full_table}",      "{stage.name.title()} Table")
        dbutils.widgets.text("run_date",       datetime.now().strftime("%Y-%m-%d"), "Run Date")
        dbutils.widgets.text("write_mode",     "append", "Write Mode (ignored when merge_keys are set)")

        SOURCE_TABLE = dbutils.widgets.get("{source_param}")
        TARGET_TABLE = dbutils.widgets.get("{target_param}")
        RUN_DATE     = dbutils.widgets.get("run_date")
        WRITE_MODE   = dbutils.widgets.get("write_mode")
        QUARANTINE_TABLE = "{quarantine_table}"

        # COMMAND ----------
        # ── Ensure the target schema exists before anything writes to it (TARGET_TABLE
        # ── and QUARANTINE_TABLE share the same schema) — the catalog itself must
        # ── already exist; creating a catalog needs metastore-admin privileges this
        # ── notebook doesn't assume.
        spark.sql(f"CREATE SCHEMA IF NOT EXISTS {{'.'.join(TARGET_TABLE.split('.')[:2])}}")

        # COMMAND ----------
        # ── Read '{prev_stage.name}' ──────────────────────────────────────────────
        df = spark.read.table(SOURCE_TABLE).filter(F.col("_run_date") == RUN_DATE)
        source_count = df.count()
        print(f"[{stage.name}] '{prev_stage.name}' rows for {{RUN_DATE}}: {{source_count}}")

        # COMMAND ----------
        # ── Transformations (auto-generated from this stage's mappings[]) ────────
        {transformations_str}

        # COMMAND ----------
        # ── Data expectations: fail_pipeline (checked first — halts before any write) ─
        {fail_block_str}

        # COMMAND ----------
        # ── Data expectations: quarantine (violating rows routed to a separate table) ─
        _q_parts = []
        {quarantine_block_str}

        if _q_parts:
            df_quarantine = _q_parts[0]
            for _part in _q_parts[1:]:
                df_quarantine = df_quarantine.unionByName(_part)
            quarantine_count = df_quarantine.count()
            print(f"[{stage.name}] ⚠️  {{quarantine_count}} row(s) quarantined")
            (
                df_quarantine
                .withColumn("_quarantined_at", F.current_timestamp())
                .write.format("delta").mode("append").option("mergeSchema", "true")
                .saveAsTable(QUARANTINE_TABLE)
            )
        else:
            quarantine_count = 0

        # COMMAND ----------
        # ── Data expectations: drop_row (violating rows silently removed) ────────────
        {drop_block_str}

        # COMMAND ----------
        # ── Data expectations outside the supported rule grammar ─────────────────────
        {skip_comment}

        # COMMAND ----------
        # ── Deduplicate within this batch (required before MERGE; also protects append) ─
        {_reindent(dedup_block)}
        dedup_count = source_count - quarantine_count - df.count()

        # COMMAND ----------
        # ── Select this stage's final columns (+ audit columns, carried forward) ──
        df_out = df.select(
            "{'", "'.join(all_target_cols)}",
            "_ingested_at", "_source_file", "_run_date"
        )

        # COMMAND ----------
        {_reindent(write_block)}
        print(f"[{stage.name}] ✅ Wrote/merged {{out_count}} rows into {{TARGET_TABLE}}")

        # COMMAND ----------
        dbutils.notebook.exit(json.dumps({{
            "status": "SUCCESS", "{prev_stage.name}_count": source_count,
            "{stage.name}_count": out_count, "quarantine_count": quarantine_count,
        }}))
    """)


def generate_integration_test_notebook(spec: PipelineSpec) -> str:
    """Loads Component 2's test fixtures directly from Unity Catalog
    (spec.test_synthetic_input_table / test_expected_output_table — written
    by the generated 00_load_test_fixtures.py notebook) and validates:
      1. schema conformance  2. per-test-case field values
      3. declarative data_expectations against the live Silver/quarantine tables.

    fail_pipeline-type expectations are intentionally NOT re-validated here with
    violating data: a single violating row in this same batch would raise inside
    02_transform_to_silver before anything is written, aborting every other
    assertion in this notebook. They're enforced (and documented) directly in
    the Silver notebook's generated code instead — see the fail_pipeline block
    in 02_transform_silver.py.
    """
    final_stage = spec.final_stage
    pk_target = spec.primary_key_field.target_field
    separator60 = "=" * 60
    notebook_num = len(spec.stages) + 1

    schema_lines = ",\n".join(
        f'    "{fm.target_field}": "{fm.simple_type_string}"' for fm in final_stage.fields
    )

    quar_exps = [e for e in final_stage.expectations if e.action_on_failure == "quarantine" and e.parsed]
    drop_exps = [e for e in final_stage.expectations if e.action_on_failure == "drop_row" and e.parsed]
    fail_exps = [e for e in final_stage.expectations if e.action_on_failure == "fail_pipeline" and e.parsed]

    exp_check_blocks = []
    for e in quar_exps + drop_exps:
        cond = _spark_condition(e.parsed)
        exp_check_blocks.append(
            f'_viol = df_final.filter(~({cond})).count()\n'
            f'assert_test("EXP-{e.name}", "No {final_stage.name} rows violate \'{e.rule}\' ({e.action_on_failure})",\n'
            f'            _viol == 0, f"{{_viol}} violating row(s) still in {final_stage.name}")'
        )
    exp_check_str = _reindent("\n\n".join(exp_check_blocks) or "# (no drop_row/quarantine expectations to check)")

    fail_doc_lines = _reindent("\n".join(
        f'print("  ℹ️  \'{e.name}\' ({e.rule}) — enforced via raise in the \'{final_stage.name}\' transform notebook, '
        f'not re-tested in this batch (see module docstring)")' for e in fail_exps
    ) or 'print("  (no fail_pipeline expectations)")')

    # ── Lightweight row-count sanity checks on intermediate stages ───────────
    # (full schema + value assertions only make sense for the final stage,
    # which is what Component 2's expected_output fixture table was built against)
    intermediate_stages = spec.transform_stages[:-1]
    intermediate_blocks = [
        f'_cnt = spark.read.table("{s.full_table}").filter(F.col("_run_date") == RUN_DATE).count()\n'
        f'assert_test("ROWCOUNT-{s.name}", "Stage \'{s.name}\' ({s.full_table}) produced rows for this run",\n'
        f'            _cnt > 0, "0 rows found")'
        for s in intermediate_stages
    ]
    intermediate_check_str = _reindent(
        "\n\n".join(intermediate_blocks) or "# (no intermediate stages between ingest and the final stage)"
    )

    quarantine_table = f"{final_stage.catalog}.{final_stage.schema}.{final_stage.table}_quarantine"
    final_param = f"{final_stage.name}_table"

    return textwrap.dedent(f"""\
        {_reindent(_notebook_header(
            f"{notebook_num:02d} — Integration Tests",
            f"Loads Component 2's test fixtures from Unity Catalog and validates '{final_stage.name}' + quarantine table output."
        ))}

        # COMMAND ----------
        import json
        import pyspark.sql.functions as F
        from pyspark.sql.types import *
        from datetime import datetime

        # COMMAND ----------
        # ── Parameters ──────────────────────────────────────────────────────────
        dbutils.widgets.text("{final_param}",            "{final_stage.full_table}", "{final_stage.name.title()} Table")
        dbutils.widgets.text("run_date",                 datetime.now().strftime("%Y-%m-%d"), "Run Date")
        dbutils.widgets.text("synthetic_input_table",    "{spec.test_synthetic_input_table}", "Synthetic Input Table")
        dbutils.widgets.text("expected_output_table",    "{spec.test_expected_output_table}", "Expected Output Table")

        FINAL_TABLE           = dbutils.widgets.get("{final_param}")
        RUN_DATE              = dbutils.widgets.get("run_date")
        SYNTHETIC_INPUT_TABLE = dbutils.widgets.get("synthetic_input_table")
        EXPECTED_OUTPUT_TABLE = dbutils.widgets.get("expected_output_table")
        QUARANTINE_TABLE      = "{quarantine_table}"

        # COMMAND ----------
        # ── Load test fixtures from Unity Catalog (written by 00_load_test_fixtures) ──
        total_cases = spark.read.table(SYNTHETIC_INPUT_TABLE).count()
        expected_rows = [r.asDict() for r in spark.read.table(EXPECTED_OUTPUT_TABLE).collect()]
        print(f"[test] {{total_cases}} total test cases in {{SYNTHETIC_INPUT_TABLE}} "
              f"({{len(expected_rows)}} expected in '{final_stage.name}')")

        # COMMAND ----------
        # ── Load final-stage output ───────────────────────────────────────────────
        df_final = spark.read.table(FINAL_TABLE)

        # ── Test runner ──────────────────────────────────────────────────────────
        results   = []
        failures  = []

        def assert_test(tc_id, description, condition, detail=""):
            entry = {{"tc_id": tc_id, "description": description,
                      "status": "PASS" if condition else "FAIL", "detail": detail}}
            results.append(entry)
            if not condition:
                failures.append(entry)
                print(f"  ❌ [{{tc_id}}] {{description}}: {{detail}}")
            else:
                print(f"  ✅ [{{tc_id}}] {{description}}")

        # COMMAND ----------
        # ── Schema validation (derived from mappings[], not hardcoded) ───────────
        EXPECTED_SCHEMA = {{
        {_reindent(schema_lines)}
        }}
        actual_types = {{f.name: f.dataType.simpleString() for f in df_final.schema.fields}}
        for col_name, expected_type in EXPECTED_SCHEMA.items():
            assert_test(
                f"SCH-{{col_name}}", f"Column '{{col_name}}' has type '{{expected_type}}'",
                actual_types.get(col_name) == expected_type,
                f"Got '{{actual_types.get(col_name)}}'"
            )

        # COMMAND ----------
        # ── Per-test-case value assertions ───────────────────────────────────────
        print("\\n--- Value Assertions ---")
        PK_TARGET = "{pk_target}"
        _meta_cols = {{"_tc_id", "_scenario", "_edge_case"}}
        for exp in expected_rows:
            tc_id  = exp["_tc_id"]
            pk_val = exp.get(PK_TARGET)
            if not pk_val:
                continue
            row = df_final.filter(F.col(PK_TARGET) == pk_val).first()
            if row is None:
                assert_test(tc_id, f"Row with {{PK_TARGET}}='{{pk_val}}' exists in '{final_stage.name}'",
                            False, "Row not found")
                continue
            for col, expected_str in exp.items():
                if col in _meta_cols:
                    continue
                actual = row[col]
                if expected_str is None or expected_str == "":
                    assert_test(tc_id, f"{{col}} is null", actual is None,
                                f"Expected null, got '{{actual}}'")
                else:
                    assert_test(tc_id, f"{{col}} = '{{expected_str}}'",
                                str(actual) == expected_str,
                                f"Got '{{actual}}'")

        # COMMAND ----------
        # ── Declarative data-expectation checks (drop_row / quarantine) ──────────
        print("\\n--- Data Expectation Checks ---")
        {exp_check_str}

        # COMMAND ----------
        # ── fail_pipeline expectations — documented, not re-tested in this batch ──
        {fail_doc_lines}

        # COMMAND ----------
        # ── Intermediate-stage row-count sanity checks ────────────────────────────
        print("\\n--- Intermediate Stage Checks ---")
        {intermediate_check_str}

        # COMMAND ----------
        # ── Summary ──────────────────────────────────────────────────────────────
        total  = len(results)
        passed = sum(1 for r in results if r["status"] == "PASS")
        failed = total - passed
        print(f"\\n{separator60}")
        print(f"  TEST SUMMARY: {{passed}}/{{total}} passed, {{failed}} failed")
        print(f"{separator60}")

        exit_payload = json.dumps({{
            "status":       "SUCCESS" if failed == 0 else "FAILURE",
            "total_tests":  total, "passed": passed, "failed": failed,
            "failed_tests": [r["tc_id"] for r in failures],
        }})

        if failed > 0:
            raise Exception(f"Integration tests FAILED:\\n{{exit_payload}}")
        else:
            dbutils.notebook.exit(exit_payload)
    """)


# ─────────────────────────────────────────────────────────────────────────────
# DAB YAML generators
# ─────────────────────────────────────────────────────────────────────────────

def generate_databricks_yml(spec: PipelineSpec) -> str:
    target_blocks = []
    for i, env in enumerate(spec.target_environments):
        target_blocks.append(f'  {env}:')
        if i == 0:
            target_blocks.append('    mode: development')
            target_blocks.append('    default: true')
        else:
            target_blocks.append('    mode: production' if env == 'prod' else '    mode: development')
        target_blocks.append('    variables:')
        target_blocks.append(f'      catalog: "{spec.target_catalog}"')
        target_blocks.append(f'      env: "{env}"')
        target_blocks.append(f'      source_path: "{spec.source_location.rstrip("/")}/{env}/"')
    targets_str = "\n".join(target_blocks)

    return textwrap.dedent(f"""\
        # Databricks Asset Bundle — Auto-generated by DPBA Component 3
        # Source: {spec.pipeline_name} (bundle_metadata / target_configurations)

        bundle:
          name: {spec.bundle_name}

        workspace:
          host: ${{var.workspace_host}}

        variables:
          workspace_host:
            description: "Databricks workspace URL"
            default: "https://your-workspace.azuredatabricks.net"

          catalog:
            description: "Unity Catalog catalog name"
            default: "{spec.target_catalog}"

          env:
            description: "Deployment environment"
            default: "{spec.target_environments[0]}"

          source_path:
            description: "Path to raw source extract files"
            default: "{spec.source_location}"

        include:
          - resources/*.yml

        targets:
        {_reindent(targets_str)}
    """)


def _job_table_var(spec: PipelineSpec, stage: PipelineStage) -> str:
    return f"${{var.catalog}}.{stage.schema}.{stage.table}"


def _job_fixture_table_var(spec: PipelineSpec, table_suffix: str) -> str:
    """Same ${var.catalog} substitution as _job_table_var (so -t prod/staging
    correctly repoints the job at a different catalog), but only when the
    test-fixture catalog wasn't explicitly set to something different from
    the pipeline's own catalog — an explicit override in
    test_data_specifications.unity_catalog.catalog is a deliberate choice
    and is respected as a literal, not silently re-pointed per environment."""
    if spec.test_catalog == spec.target_catalog:
        return f"${{var.catalog}}.{spec.test_schema}.{spec.test_table_prefix}_{table_suffix}"
    return f"{spec.test_catalog}.{spec.test_schema}.{spec.test_table_prefix}_{table_suffix}"


def _build_task_blocks(spec: PipelineSpec) -> list[str]:
    """One YAML task per stage transition, chained via depends_on in stage
    order — however many stages the mapping JSON declares (2, 3, N) — plus
    an independent 'load_test_fixtures' task (no dependencies, runs in
    parallel with ingest) that 'run_integration_tests' also waits on."""
    blocks: list[str] = []

    blocks.append(textwrap.dedent(f"""\
        - task_key: load_test_fixtures
          job_cluster_key: test_utility_cluster
          notebook_task:
            notebook_path: ${{workspace.root_path}}/files/notebooks/00_load_test_fixtures
            base_parameters:
              synthetic_input_table: "{_job_fixture_table_var(spec, 'synthetic_input')}"
              expected_output_table: "{_job_fixture_table_var(spec, 'expected_output')}"
          timeout_seconds: 1800
          max_retries: 1"""))

    ingest = spec.ingest_stage
    ingest_task_key = f"ingest_to_{ingest.name}"
    blocks.append(textwrap.dedent(f"""\
        - task_key: {ingest_task_key}
          job_cluster_key: pipeline_shared_cluster
          notebook_task:
            notebook_path: ${{workspace.root_path}}/files/notebooks/01_ingest_{ingest.name}
            base_parameters:
              source_path: "${{var.source_path}}"
              {ingest.name}_table: "{_job_table_var(spec, ingest)}"
              run_date: "{{{{job.start_time.iso_date}}}}"
          timeout_seconds: 3600
          max_retries: 1"""))

    prev_task_key, prev_stage = ingest_task_key, ingest
    for i, stage in enumerate(spec.transform_stages, start=1):
        task_key = f"transform_to_{stage.name}"
        notebook_num = f"{i + 1:02d}"
        blocks.append(textwrap.dedent(f"""\
            - task_key: {task_key}
              depends_on:
                - task_key: {prev_task_key}
              job_cluster_key: pipeline_shared_cluster
              notebook_task:
                notebook_path: ${{workspace.root_path}}/files/notebooks/{notebook_num}_transform_{stage.name}
                base_parameters:
                  {prev_stage.name}_table: "{_job_table_var(spec, prev_stage)}"
                  {stage.name}_table: "{_job_table_var(spec, stage)}"
                  run_date: "{{{{job.start_time.iso_date}}}}"
                  write_mode: "append"
              timeout_seconds: 3600
              max_retries: 1"""))
        prev_task_key, prev_stage = task_key, stage

    test_notebook_num = f"{len(spec.stages) + 1:02d}"
    blocks.append(textwrap.dedent(f"""\
        - task_key: run_integration_tests
          depends_on:
            - task_key: {prev_task_key}
            - task_key: load_test_fixtures
          job_cluster_key: test_utility_cluster
          notebook_task:
            notebook_path: ${{workspace.root_path}}/files/notebooks/{test_notebook_num}_integration_tests
            base_parameters:
              {spec.final_stage.name}_table: "{_job_table_var(spec, spec.final_stage)}"
              run_date: "{{{{job.start_time.iso_date}}}}"
              synthetic_input_table: "{_job_fixture_table_var(spec, 'synthetic_input')}"
              expected_output_table: "{_job_fixture_table_var(spec, 'expected_output')}"
          timeout_seconds: 1800
          max_retries: 0    # never auto-retry failed tests — require human approval"""))

    return blocks


def generate_job_yml(spec: PipelineSpec) -> str:
    job_name = spec.job_name
    spark_conf_lines = "\n".join(
        f'                      "{k}": "{v}"' for k, v in spec.cluster_spark_conf.items()
    ) or '                      "spark.databricks.delta.preview.enabled": "true"'
    stage_chain = " → ".join(s.name for s in spec.stages)
    tasks_str = _reindent("\n\n".join(_build_task_blocks(spec)), indent="                ")

    return textwrap.dedent(f"""\
        # DAB Job Resource — Auto-generated by DPBA Component 3
        # {len(spec.stages) + 1}-task pipeline, one task per stage transition: {stage_chain} → integration_tests
        # pipeline_shared_cluster (autoscaling, sized from workflow_specification.job_clusters[0])
        # runs the ingest/transform stages; test_utility_cluster (single-node) runs the
        # lightweight fixture-load + integration-test tasks — least compute each task needs.

        resources:
          jobs:
            {job_name}_job:
              name: "{job_name}_[${{bundle.target}}]"
              description: "{spec.job_description}"

              # ── Cluster ───────────────────────────────────────────────────────
              # ⚠️  node_type_id is cloud-provider-specific (this one assumes AWS unless
              # ⚠️  workflow_specification.job_clusters[0].new_cluster.node_type_id was set
              # ⚠️  in the mapping JSON) — on Azure/GCP, replace it with a valid instance
              # ⚠️  type for your workspace before deploying, or `databricks bundle validate`
              # ⚠️  / the job run will fail with an invalid-node-type error.
              job_clusters:
                - job_cluster_key: pipeline_shared_cluster
                  new_cluster:
                    spark_version: "{spec.cluster_spark_version}"
                    node_type_id: "{spec.cluster_node_type_id}"
                    autoscale:
                      min_workers: 1
                      max_workers: {spec.cluster_num_workers}
                    spark_conf:
        {spark_conf_lines}
                    data_security_mode: "SINGLE_USER"

                # Single-node, driver-only cluster for the lightweight utility tasks
                # (load_test_fixtures: writes a few dozen literal rows; run_integration_tests:
                # counts/filters over those same small tables) — these never touch real data
                # volume, so they get the cheapest possible compute instead of sharing the
                # autoscaling cluster sized for the actual ingest/transform stages.
                - job_cluster_key: test_utility_cluster
                  new_cluster:
                    spark_version: "{spec.cluster_spark_version}"
                    node_type_id: "{spec.cluster_node_type_id}"
                    num_workers: 0
                    spark_conf:
                      "spark.databricks.cluster.profile": "singleNode"
                      "spark.master": "local[*]"
                    custom_tags:
                      "ResourceClass": "SingleNode"
                    data_security_mode: "SINGLE_USER"

              # ── Tasks (dynamically built from the stage chain) ──────────────────
              tasks:
                {tasks_str}

              # ── Schedule (PAUSED in dev by default) ──────────────────────────
              schedule:
                quartz_cron_expression: "0 0 6 * * ?"
                timezone_id: "UTC"
                pause_status: PAUSED

              # ── Notifications ─────────────────────────────────────────────────
              email_notifications:
                on_failure:
                  - "your-team@example.com"
                no_alert_for_skipped_runs: true

              # ── Tags ──────────────────────────────────────────────────────────
              tags:
                project:      "dpba"
                pipeline:     "{job_name}"
                environment:  "${{var.env}}"
                generated_by: "DPBA-Component3"
    """)


# ─────────────────────────────────────────────────────────────────────────────
# Human-in-the-Loop Review
# ─────────────────────────────────────────────────────────────────────────────

def human_review(spec: PipelineSpec, output_dir: str) -> bool:
    print("\n" + "═" * 70)
    print("  COMPONENT 3 — PIPELINE BUILDER: PRE-GENERATION REVIEW")
    print("═" * 70)
    print(f"\n  Pipeline chain : {' → '.join(s.name for s in spec.stages)}  ({len(spec.stages)} stages)")
    print(f"  Catalog        : {spec.target_catalog}")
    print(f"  Final merge keys: {spec.final_stage.merge_keys or '(none — append mode)'}")
    print(f"  Output         : {output_dir}")
    print(f"\n  Field Mappings & Expectations:")
    print_spec_table(spec)
    print()
    print("  Files to be generated:")
    print(f"    ├── notebooks/01_ingest_{spec.ingest_stage.name}.py")
    for i, stage in enumerate(spec.transform_stages, start=1):
        print(f"    ├── notebooks/{i + 1:02d}_transform_{stage.name}.py")
    print(f"    ├── notebooks/{len(spec.stages) + 1:02d}_integration_tests.py")
    print("    ├── resources/pipeline_job.yml")
    print("    └── databricks.yml")
    print()

    answer = input("  [HITL] Generate pipeline code? [y=proceed / n=abort]: ").strip().lower()
    return answer == "y"


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def run(spec: PipelineSpec, output_dir: str, test_cases: list,
        skip_hitl: bool = False) -> dict[str, str]:
    """
    Args:
        test_cases: Component 2's generated TestCase list — used to render
                    notebooks/00_load_test_fixtures.py (see
                    component2_data_generator.generate_load_fixtures_notebook).
                    The *generation logic* for that notebook's content lives
                    in Component 2; Component 3 just assembles it into the
                    final deployable bundle alongside its own notebooks.
    """
    print("\n" + "═" * 70)
    print("  COMPONENT 3 — DETERMINISTIC PIPELINE BUILDER")
    print("═" * 70)

    if not skip_hitl:
        approved = human_review(spec, output_dir)
        if not approved:
            print("  [builder] ❌ Aborted by user.")
            return {}

    notebooks_dir = os.path.join(output_dir, "notebooks")
    resources_dir = os.path.join(output_dir, "resources")
    os.makedirs(notebooks_dir, exist_ok=True)
    os.makedirs(resources_dir, exist_ok=True)

    artifacts: dict[str, str] = {}

    def _write(rel_path: str, content: str) -> str:
        abs_path = os.path.join(output_dir, rel_path)
        with open(abs_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"  [builder] ✅ {rel_path}")
        return abs_path

    artifacts["load_fixtures_notebook"] = _write(
        "notebooks/00_load_test_fixtures.py", generate_load_fixtures_notebook(spec, test_cases)
    )
    artifacts[f"ingest_notebook_{spec.ingest_stage.name}"] = _write(
        f"notebooks/01_ingest_{spec.ingest_stage.name}.py", generate_ingest_notebook(spec)
    )
    for i, stage in enumerate(spec.transform_stages, start=1):
        artifacts[f"transform_notebook_{stage.name}"] = _write(
            f"notebooks/{i + 1:02d}_transform_{stage.name}.py", generate_transform_notebook(spec, i)
        )
    artifacts["test_notebook"] = _write(
        f"notebooks/{len(spec.stages) + 1:02d}_integration_tests.py",
        generate_integration_test_notebook(spec)
    )
    artifacts["job_yml"]    = _write("resources/pipeline_job.yml", generate_job_yml(spec))
    artifacts["bundle_yml"] = _write("databricks.yml", generate_databricks_yml(spec))

    print(f"\n  [builder] ✅ Pipeline generation complete → {output_dir}")
    print("  Next steps:")
    print(f"    1. Test fixtures load into Unity Catalog automatically (task 'load_test_fixtures' —")
    print(f"       writes {spec.test_synthetic_input_table} / {spec.test_expected_output_table})")
    print("    2. cd into the output directory")
    print("    3. databricks bundle validate")
    print("    4. databricks bundle deploy")
    print(f"    5. databricks bundle run {spec.job_name}_job")

    return artifacts


if __name__ == "__main__":
    from component2_data_generator import DataGenerator

    script_dir   = os.path.dirname(os.path.abspath(__file__))
    default_json = os.path.join(script_dir, "sample_specs", "customer_pipeline.json")
    json_path    = sys.argv[1] if len(sys.argv) > 1 else default_json
    out_dir      = sys.argv[2] if len(sys.argv) > 2 else os.path.join(script_dir, "output", "pipeline")

    spec = parse_mapping_json(json_path)
    test_cases = DataGenerator(spec).generate()
    run(spec, output_dir=out_dir, test_cases=test_cases)
